DROP TABLE OfficalContent;
DROP TABLE OfficalInfo;
DROP TABLE AnalysisContent;
DROP TABLE AnalysisInfo;
DROP TABLE EnsembleContent;
DROP TABLE EnsembleInfo;
DROP TABLE ForecastContent;
DROP TABLE ForecastInfo;
DROP TABLE CentreInfo;
DROP TABLE TyphoonInfo;

-- TRUNCATE TABLE OfficalContent;
-- TRUNCATE TABLE OfficalInfo;
-- TRUNCATE TABLE analysiscontent;
-- TRUNCATE TABLE analysisinfo;
-- TRUNCATE TABLE EnsembleContent;
-- TRUNCATE TABLE EnsembleInfo;
-- TRUNCATE TABLE ForecastContent;
-- TRUNCATE TABLE ForecastInfo;
-- TRUNCATE TABLE CentreInfo;
-- TRUNCATE TABLE TyphoonInfo;